version: '3.3'
services:
    dbserver:
        build: ./docker/dbserver
        image: mysql:5.7
        restart: always
        volumes:
            - ./mysql-db:/var/lib/mysql
            - ./docker/dbserver/initdb.d:/docker-entrypoint-initdb.d
            - ./docker/dbserver/conf.d:/etc/mysql/conf.d
            - ./log/dbserver:/var/log/mysql
#        ports:
#            - "3314:3306"
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: sboot
            MYSQL_PASSWORD: sboot
            MYSQL_ROOT_PASSWORD: rootpassword
           
    app:
        build: ./docker/app
        image: watari/boot:0.1.0                            
        depends_on:
            - dbserver
        ports:
            - "18001:8080"
        volumes:
            - .:/app
        environment:
            JAR_TARGET: boot-get-started-0.0.1-SNAPSHOT.jar

    myadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - dbserver
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: dbserver
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "18000:80"

volumes:
    mysql-db:
        driver: local